### ISSUE TITLE
add chmod in Dockerfile

### ISSUE THREAD

**Issue by evshvarov** [jrpereirajr/zap-api-scan-sample#1]
I think it's possible to add
```
chmod 777 -R zap-pool
```
in Dockerfile
?

**Comment by jrpereirajr** [comment]
Hi Evgeny!
This directory is out of docker container, it is setup in [docker-compose.yaml](https://github.com/jrpereirajr/zap-api-scan-sample/blob/bf45da75c244f4c47059789079285446197f65af/docker-compose.yml#L27)
I only was able to make this directory RW running the chmod command in the host, instead of the container... Were you able to perform such changes in the project and get things working properly?
Robert Cemper wrote a review saying that in Windows, this rights wasn't necessary. It makes sense due I'm using docker on WLS running a Ubuntu image.
