### ISSUE TITLE
Online Demo is broken

### ISSUE THREAD

**Issue by rcemper** [jrpereirajr/zap-api-scan-sample#5]

**Comment by jrpereirajr** [comment]
Hi @rcemper. 

Thanks for warnimg about the broken link.

I removed the online demo from OEX and send it for approvement. I done that because this project needs resource which I can't attend to be available on GCP, like a ZAP environment. Currently, ths only could be done by trying the project locally, using Docker.

However, I kept the GCP build workflow because ZAP has a workflow which performs security scanning on a REST API hosted in IRIS, as metioned [here](https://github.com/jrpereirajr/zap-api-scan-sample#github-action).

José
